(load "/projects/actr/actr7/load-act-r.lisp")
(load "/projects/actr/models/PSS_RAPM_Model/devel4/rapm-device.lisp")
(load "/projects/actr/models/PSS_RAPM_Model/devel4/rapm-simulations.lisp")
(load "/projects/actr/models/PSS_RAPM_Model/devel4/rapm-model.lisp")
(general-simulations 200) ;; :tickvals '(20))
(quit)
